# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewiOSOfQFNU' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'DJRefresh', '~> 1.0.5'
    pod 'MJRefresh'
       pod 'TFHpple', '~> 2.0.0'
   pod 'NHHUDExtend', '~> 1.0.1'
  # Pods for NewiOSOfQFNU

  target 'NewiOSOfQFNUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewiOSOfQFNUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
